services:
  julia-build:
    container_name: julia-build
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=sphere
      - METHOD=default
      - D=10
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '50'; do julia /root/src/main.jl $$D abc cvt rosenbrock; done"]
  
  julia-figure:
    container_name: julia-figure
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.figure
    working_dir: /root
    volumes:
      - ./src/result:/root/result
      - ./src/log:/root/log
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=sphere
      - METHOD=default
      - D=10
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '50'; do julia make-plot.jl $$D abc cvt rosenbrock fitness; done"]

networks:
  default:
    driver: bridge