services:
  julia-build:
    container_name: julia-build
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=sphere rosenbrock rastrigin griewank schwefel ackley michalewicz
      - METHOD=default de abc
      - D=10
      - LOOP=1 2 3 4 5
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for i in $$LOOP; do echo $$i; for f in $$FUNCTION; do for d in $$D; do for m in $$METHOD; do julia /root/src/main.jl $$d $$m cvt $$f; done; done; done; done"]
  
  julia-figure:
    container_name: julia-figure
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.figure
    working_dir: /root
    volumes:
      - ./src/result:/root/result
      - ./src/log:/root/log
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=sphere rosenbrock rastrigin griewank schwefel ackley michalewicz
      - METHOD=default de abc
      - D=10
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for m in $$METHOD; do for f in $$FUNCTION; do for d in $$D; do julia make-plot.jl $$d $$m cvt $$f fitness; done; done; done"]

networks:
  default:
    driver: bridge