services:
  julia-build:
    container_name: julia
    tty: true
    build:
      context: .
      dockerfile: Dockerfile-edit
    working_dir: /root/workdir
    volumes:
      - ./src:/root/workdir
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo

networks:
  default:
    driver: bridge
