services:
  julia-test-1:
    container_name: julia-test-1
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=sphere rastrigin
      - METHOD=de abc
      - D=10 50
      - LOOP=1 2
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 8G
    command: ["sh", "-c", "for i in $$LOOP; do echo $$i; for f in $$FUNCTION; do for d in $$D; do for m in $$METHOD; do julia /root/src/main.jl $$d $$m cvt $$f; done; done; done; done"]
  julia-test-2:
    container_name: julia-test-2
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=sphere rastrigin
      - METHOD=abc de
      - D=10 50
      - LOOP=1 2
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 8G
    command: ["sh", "-c", "for i in $$LOOP; do echo $$i; for f in $$FUNCTION; do for d in $$D; do for m in $$METHOD; do julia /root/src/main.jl $$d $$m cvt $$f; done; done; done; done"]
  julia-test-3:
    container_name: julia-test-3
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=rastrigin sphere
      - METHOD=de abc
      - D=10 50
      - LOOP=1 2
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 8G
    command: ["sh", "-c", "for i in $$LOOP; do echo $$i; for f in $$FUNCTION; do for d in $$D; do for m in $$METHOD; do julia /root/src/main.jl $$d $$m cvt $$f; done; done; done; done"]
  julia-test-4:
    container_name: julia-test-4
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=rastrigin sphere
      - METHOD=abc de
      - D=10 50
      - LOOP=1 2
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 8G
    command: ["sh", "-c", "for i in $$LOOP; do echo $$i; for f in $$FUNCTION; do for d in $$D; do for m in $$METHOD; do julia /root/src/main.jl $$d $$m cvt $$f; done; done; done; done"]

networks:
  default:
    driver: bridge