services:
  julia-build:
    container_name: julia
    tty: true
    build: .
    working_dir: /root
    volumes:
      - ./workdir:/root/workdir
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
  julia-run-ds:
    container_name: map_elites-ds
    tty: true
    build:
      context: .
      dockerfile: Dockerjuliarun
    working_dir: /root/workdir
    volumes:
      - ./workdir:/root/workdir
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["julia", "/root/workdir/main.jl", "default", "sphere"]
  julia-run-as:
    container_name: map_elites-as
    tty: true
    build:
      context: .
      dockerfile: Dockerjuliarun
    working_dir: /root/workdir
    volumes:
      - ./workdir:/root/workdir
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["julia", "/root/workdir/main.jl", "abc", "sphere"]

networks:
  default:
    driver: bridge
    