services:
  julia-run-default-sphere:
    container_name: "julia-run-default-sphere"
    tty: true
    build:
      context: .
      dockerfile: Dockerjuliarun
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=sphere
      - METHOD=default
      - D=2
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '20' '50' '100' '200' '500' '1000'; do julia /root/src/main.jl default sphere $$D; done"]
  julia-run-abc-sphere:
    container_name: "julia-run-abc-sphere"
    tty: true
    build:
      context: .
      dockerfile: Dockerjuliarun
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=sphere
      - METHOD=abc
      - D=2
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '20' '50' '100' '200' '500' '1000'; do julia /root/src/main.jl abc sphere $$D; done"]
  julia-run-default-rosenbrock:
    container_name: "julia-run-default-rosenbrock"
    tty: true
    build:
      context: .
      dockerfile: Dockerjuliarun
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=rosenbrock
      - METHOD=default
      - D=2
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '20' '50' '100' '200' '500' '1000'; do julia /root/src/main.jl default rosenbrock $$D; done"]
  julia-run-abc-rosenbrock:
    container_name: "julia-run-abc-rosenbrock"
    tty: true
    build:
      context: .
      dockerfile: Dockerjuliarun
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=rosenbrock
      - METHOD=abc
      - D=2
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '20' '50' '100' '200' '500' '1000'; do julia /root/src/main.jl abc rosenbrock $$D; done"]

networks:
  default:
    driver: bridge