services:
  julia-run-default-sphere:
    container_name: "julia-run-default-sphere"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=sphere
      - METHOD=default
      - D=2
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for i in {1..20}; do for D in '10' '20' '50' '100' '200' '500' '1000'; do julia /root/src/main.jl $$D default cvt sphere; done"]
  julia-run-abc-sphere:
    container_name: "julia-run-abc-sphere"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=sphere
      - METHOD=abc
      - D=2
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '20' '50' '100' '200' '500' '1000'; do julia /root/src/main.jl $$D abc cvt sphere; done"]
  julia-run-de-sphere:
    container_name: "julia-run-de-sphere"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=sphere
      - METHOD=de
      - D=2
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '20' '50' '100' '200' '500' '1000'; do julia /root/src/main.jl $$D de cvt sphere; done"]
  julia-run-default-rastrigin:
    container_name: "julia-run-default-rastrigin"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=rastrigin
      - METHOD=default
      - D=2
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '20' '50' '100' '200' '500' '1000'; do julia /root/src/main.jl $$D default cvt rastrigin; done"]
  julia-run-abc-rastrigin:
    container_name: "julia-run-abc-rastrigin"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=rastrigin
      - METHOD=abc
      - D=2
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '20' '50' '100' '200' '500' '1000'; do julia /root/src/main.jl $$D abc cvt rastrigin; done"]
  julia-run-de-rastrigin:
    container_name: "julia-run-de-rastrigin"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=rastrigin
      - METHOD=de
      - D=2
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '20' '50' '100' '200' '500' '1000'; do julia /root/src/main.jl $$D de cvt rastrigin; done"]
  julia-run-default-rosenbrock:
    container_name: "julia-run-default-rosenbrock"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=rosenbrock
      - METHOD=default
      - D=2
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '20' '50' '100' '200' '500' '1000'; do julia /root/src/main.jl $$D default cvt rosenbrock; done"]
  julia-run-abc-rosenbrock:
    container_name: "julia-run-abc-rosenbrock"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=rosenbrock
      - METHOD=abc
      - D=2
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '20' '50' '100' '200' '500' '1000'; do julia /root/src/main.jl $$D abc cvt rosenbrock; done"]
  julia-run-de-rosenbrock:
    container_name: "julia-run-de-rosenbrock"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=rosenbrock
      - METHOD=de
      - D=2
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '20' '50' '100' '200' '500' '1000'; do julia /root/src/main.jl $$D de cvt rosenbrock; done"]
  julia-run-default-griewank:
    container_name: "julia-run-default-griewank"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=griewank
      - METHOD=default
      - D=2
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '20' '50' '100' '200' '500' '1000'; do julia /root/src/main.jl $$D default cvt griewank; done"]
  julia-run-abc-griewank:
    container_name: "julia-run-abc-griewank"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=griewank
      - METHOD=abc
      - D=2
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '20' '50' '100' '200' '500' '1000'; do julia /root/src/main.jl $$D abc cvt griewank; done"]
  julia-run-de-griewank:
    container_name: "julia-run-de-griewank"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/src
    volumes:
      - ./src:/root/src
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=griewank
      - METHOD=de
      - D=2
    deploy:
      resources:
        limits:
          cpus: 4.5
          memory: 8G
    command: ["sh", "-c", "for D in '10' '20' '50' '100' '200' '500' '1000'; do julia /root/src/main.jl $$D de cvt griewank; done"]

networks:
  default:
    driver: bridge