services:
  julia-dev:
    container_name: julia-dev
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/
    volumes:
      - ./src/result:/root/result
      - ./src/log:/root/log
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=sphere rosenbrock rastrigin griewank schwefel ackley michalewicz
      - METHOD=default de abc
      - D=10 50 100
      - LOOP=1 2
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 8G
    command: ["bash"]

  julia-figure:
    container_name: julia-figure
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.figure
    working_dir: /root/
    volumes:
      - ./src/result:/root/result
      - ./src/log:/root/log
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      - FUNCTION=sphere rosenbrock rastrigin
      - METHOD=abc
      - D=10 50 100
      - CVT_UPDATE=0
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 8G
    # command: ["sh", "-c", "for f in $$FUNCTION; do for d in $$D; do julia make-plot.jl $$d $$f; do for m in $$METHOD; for cup in $$CVT_UPDATE; do julia make-vorn.jl $$d $$f cvt $$m $$cup; done; done; done; done"]
    # command: ["sh", "-c", "for d in $$D; do for m in $$METHOD; do for cup in $$CVT_UPDATE; do julia make-vorn.jl $$d $$f cvt $$m $$cup; done; done; done"]
    # command: ["sh", "-c", "for f in $$FUNCTION; do for d in $$D; do julia make-plot.jl $$d $$f; done; done"]
    # command: ["julia", "make-table.jl"]
    # command: ["julia", "make-vorn.jl", "10", "abc", "cvt", "sphere", "4"]
    command: ["sh", "-c", "for f in $$FUNCTION; do for m in $$METHOD; do for d in $$D; do for cup in $$CVT_UPDATE; do julia make-vorn.jl $$d $$m cvt $$f $$cup; done; done; done; done"]

networks:
  default:
    driver: bridge